include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enable additional lint rules
    prefer_single_quotes: true
    avoid_print: false  # Allow print statements for debugging
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore